### ISSUE TITLE
github actions で [ci skip] を試したい

### ISSUE THREAD

**Issue by msfukui** [msfukui/tdd-by-example-for-go#2]
c.f. https://srz-zumix.blogspot.com/2019/10/github-actions-ci-skip.html

問題なさそうなら、仕事でも使ってみたい。

**Comment by msfukui** [comment]
commit: 8801d2d175d987aa6e23640b9ba8b56d08eeaefa で対応してみた。

参考に書かれていたそのままだと動かなくて、prepare の steps に書かれた run は同レベルにする必要があった。（じゃないと workflow の実行自体に失敗する。）

```
jobs:
  prepare:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - run: echo "${{ github.event.head_commit.message }}"  # ←ここのインデントを steps に合わせる必要がある。

  build:
    runs-on: ubuntu-latest
    needs: prepare
```
